### ISSUE TITLE
Change Navigation Menu Name

### ISSUE THREAD

**Issue by EveEdwin** [FSOC-OSS/FSOC.V1#1]
![nav issue](https://github.com/user-attachments/assets/03d5d3c9-b6a1-42d5-b21e-2a09bfad909f)

Update the names of the navigation bar menu items to reflect the latest design changes. This will ensure consistency with the new layout and improve overall user experience.

**Comment by Sriijannn** [comment]
I have fixed the issue

**Comment by masamasaowl** [comment]
I have fixed the issue!!!

**Comment by Priya-rai121** [comment]
I have fixed the issue :)

**Comment by ujjwal006** [comment]
I have fixed the issue.

**Comment by Shashwat-Trivedi** [comment]
i have fixed this issue

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by amar641** [comment]
I have fixed the issue.

**Comment by SumeetAttri09** [comment]
i have fixed this issue

**Comment by palak413** [comment]
i have fixed the issue.
