### ISSUE TITLE
Change the content in the banner

### ISSUE THREAD

**Issue by EveEdwin** [FSOC-OSS/FSOC.V1#2]
![content home](https://github.com/user-attachments/assets/94da82c7-e3c4-41c0-8e2e-10eaefa25502)

Modify the content of the banner to align with the current project messaging and improve clarity. The new content should better reflect the purpose and key features of the application.

**Comment by Priya-rai121** [comment]
I have fixed the issue :)

**Comment by ujjwal006** [comment]
i have fixed the issue.

**Comment by Shashwat-Trivedi** [comment]
i have fixed this issue

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by EveEdwin** [comment]
@Priya-rai121 Nice written. Keep Solving
