### ISSUE TITLE
fix: Decrease the size of Download Button

### ISSUE THREAD

**Issue by EveEdwin** [FSOC-OSS/FSOC.V1#37]
![image](https://github.com/user-attachments/assets/ee41b4b2-25de-4307-8900-0c7de19df083)
Size of the Download from the App Store or Play Store is very large reduce the size to its proper length.

**Comment by justbeingashutosh** [comment]
I have fixed this issue

**Comment by Priya-rai121** [comment]
I have fixed the issue!

**Comment by ujjwal006** [comment]
I have fixed the issue

**Comment by palak413** [comment]
i have fixed the issue
