### ISSUE TITLE
fix:  Social Media Icons are very Large

### ISSUE THREAD

**Issue by EveEdwin** [FSOC-OSS/FSOC.V1#38]
![image](https://github.com/user-attachments/assets/9b25f622-f4eb-42d3-959e-5778c95f3f7e)
Decrease the size of the social media icon to fit the container use "pixels" instead of  "rem"

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by Priya-rai121** [comment]
I have fixed the issue.
