### ISSUE TITLE
The Dark Mode Button does not function as intended

### ISSUE THREAD

**Issue by justbeingashutosh** [FSOC-OSS/FSOC.V1#60]
The Dark Mode button in the navigation bar does not function as intended. 

Expected Behaviour: When clicked on the button, the theme of the website should change to Dark Mode if it is in Light Mode and to Light Mode if it is in Dark Mode.

Current Behaviour: Clicking on the button does nothing.

Steps to re-create this issue: 
Launch the html file. 
Find the Dark Mode Icon in the navigation bar and click on it. 
Nothing happens.

![Screenshot_20240930_193851](https://github.com/user-attachments/assets/87911395-6d20-4f8c-babc-670e4cebc9d2)

**Comment by EveEdwin** [comment]
Good Issue Found. Try to fix this issue.
