### ISSUE TITLE
fix: Reduce button size

### ISSUE THREAD

**Issue by EveEdwin** [FSOC-OSS/FSOC.V1#63]
![image](https://github.com/user-attachments/assets/57c0e784-17b9-4e88-a013-718a537be545)
![image](https://github.com/user-attachments/assets/ac3b7a2b-2d48-4787-88fa-38b802ef6d17)
![image](https://github.com/user-attachments/assets/bf88cdc4-1def-4ff6-a828-54d03bef2591)

Button sizes are very big try to fix this to its appropriate size.

**Comment by palak413** [comment]
i have fixed the issue
